
name: Deploy Python FastAPI App

on:
  push:
    branches:
      - main   # This will trigger the workflow on a push to the main branch
  workflow_dispatch:   # Allows for manual trigger as well

jobs:
  deploy:
    runs-on: ubuntu-latest  # Set up the environment for the job

    env:
      HOSTAWAY_ACCESS_TOKEN: ${{ secrets.HOSTAWAY_ACCESS_TOKEN }}  # Reference the secret in GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run tests (optional)
        run: |
          pytest  # If you have any tests to run, you can add them here

      - name: Deploy to Render (or other platform)
        run: |
          # For Render, use the Render CLI to deploy, or use `scp` or other commands
          # Example:
          render deploy --service my-service-name  # Replace with the actual command for deployment
          # Or you could use Docker to push if deploying with Docker:
          # docker-compose up -d
