name: Hostaway Auto-Reply Workflow

on:
  push:
    branches:
      - main   # This will trigger the workflow on a push to the main branch
  workflow_dispatch:   # Allows for manual trigger as well

jobs:
  autoreply:
    runs-on: ubuntu-latest  # Set up the environment for the job

    env:
      HOSTAWAY_ACCESS_TOKEN: ${{ secrets.HOSTAWAY_ACCESS_TOKEN }}  # Reference the secret in GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run Hostaway Auto-Reply Script
        run: |
          python hostaway_autoreply.py  # Replace with your script to handle the Hostaway interaction

      - name: Deploy (if applicable)
        run: |
          # Your deployment steps go here (if necessary)
          echo "Deployment step for Hostaway autoreply" 
